NANOSECONDS_PER_SECOND = 1_000_000_000
MILLISECONDS_PER_SECOND = 1_000

QUEUE_PUT_RETRY_TIMEOUT_SECONDS = 0.1
ASSEMBLER_RECEIVE_TIMEOUT_SECONDS = 0.1
EPISODE_ASSEMBLER_THREAD_NAME = "episode-assembler"
PER_WORKER_PENDING_EPISODE_CAPACITY = 1
SHARED_COUNTER_TYPE_CODE = "q"

CALLBACK_PROFILE_HOOK_NAMES = (
    "on_training_start",
    "on_rollout_start",
    "on_step",
    "on_rollout_end",
    "on_training_end",
)
CALLBACK_PROFILER_REPORT_TITLE = "Callback profiler"

EPISODE_ACTIONS_FIELD = "actions"
EPISODE_DONES_FIELD = "dones"
EPISODE_LAST_DONES_FIELD = "last_dones"
EPISODE_LAST_OBSERVATION_FIELD = "last_obs"
EPISODE_LOG_PROBABILITIES_FIELD = "log_probs"
EPISODE_NEW_OBSERVATION_FIELD = "new_obs"
EPISODE_REWARDS_FIELD = "rewards"
EPISODE_VALUES_FIELD = "values"

PROFILE_PHASE_POLICY_BROADCAST = "policy_broadcast"
PROFILE_PHASE_POLICY_LOADING = "policy_loading"
PROFILE_PHASE_POLICY_SERIALIZATION = "policy_serialization"
PROFILE_PHASE_EPISODE_DESERIALIZATION = "episode_deserialization"
PROFILE_PHASE_EPISODE_PACKING = "episode_packing"
PROFILE_PHASE_EPISODE_SERIALIZATION = "episode_serialization"
PROFILE_PHASE_ASSEMBLER_TRANSPORT = "assembler_transport"
PROFILE_PHASE_ASSEMBLER_WAITING = "assembler_waiting"
PROFILE_PHASE_ASSEMBLER_ACQUIRE = "assembler_acquire"
PROFILE_PHASE_PROFILER_REPORTING = "profiler_reporting"
PROFILE_PHASE_LOGGER_DUMP = "logger_dump"
PROFILE_PHASE_CALLBACK_DEBUG_PRINT = "callback_debug_print"
PROFILE_PHASE_TRANSPORT = "transport"
PROFILE_PHASE_TRANSITION_RECONSTRUCTION = "transition_reconstruction"
PROFILE_PHASE_WAITING = "waiting"

BUFFER_AVG_POLICY_LAG_KEY = "avg_policy_lag"
BUFFER_AVG_PUSH_TIME_SECONDS_KEY = "avg_push_time_seconds"
BUFFER_AVG_PUSH_WAIT_SECONDS_KEY = "avg_push_wait_seconds"
BUFFER_MAX_POLICY_LAG_KEY = "max_policy_lag"

PROFILER_LOG_PREFIX = "profiler"

TRANSPORT_PENDING_EPISODES_KEY = "pending_episodes"
TRANSPORT_MAX_PENDING_EPISODES_KEY = "max_pending_episodes"
TRANSPORT_CAPACITY_EPISODES_KEY = "capacity_episodes"
TRANSPORT_UTILIZATION_KEY = "utilization"
TRANSPORT_PENDING_BYTES_KEY = "pending_bytes"
TRANSPORT_MAX_PENDING_BYTES_KEY = "max_pending_bytes"
TRANSPORT_SENT_EPISODES_KEY = "sent_episodes"
TRANSPORT_SENT_BYTES_KEY = "sent_bytes"
TRANSPORT_RECEIVED_EPISODES_KEY = "received_episodes"

ASSEMBLY_TARGET_TRANSITIONS_KEY = "target_transitions"
ASSEMBLY_FILLING_TRANSITIONS_KEY = "filling_transitions"
ASSEMBLY_COMPLETED_BUFFERS_KEY = "completed_buffers"
ASSEMBLY_LAST_TRANSITIONS_KEY = "last_transitions"
ASSEMBLY_MAX_TRANSITIONS_KEY = "max_transitions"
ASSEMBLY_LAST_PAYLOAD_BYTES_KEY = "last_payload_bytes"
ASSEMBLY_MAX_PAYLOAD_BYTES_KEY = "max_payload_bytes"
