import struct

NANOSECONDS_PER_SECOND = 1_000_000_000
MILLISECONDS_PER_SECOND = 1_000

TRANSPORT_ACQUIRE_RETRY_TIMEOUT_SECONDS = 0.1
ASSEMBLER_RECEIVE_TIMEOUT_SECONDS = 0.1
SHARED_COUNTER_TYPE_CODE = "q"
SHARED_SLOT_INDEX_TYPE_CODE = "i"
SHARED_SIZE_TYPE_CODE = "Q"
POLICY_SNAPSHOT_SLOT_COUNT = 2
POLICY_INITIAL_SLOT_INDEX = 0
POLICY_UNPUBLISHED_VERSION = -1
EPISODE_PACKET_HEADER = struct.Struct("!BqBQ")
EPISODE_KIND_ON_POLICY_CODE = 0
EPISODE_KIND_OFF_POLICY_CODE = 1

BUFFER_AVG_POLICY_LAG_KEY = "avg_policy_lag"
BUFFER_MAX_POLICY_LAG_KEY = "max_policy_lag"

DISCARD_INFO_KEY = "discard"
EPISODE_END_REASON_INFO_KEY = "episode_end_reason"
META_INFO_PREFIX = "meta_"
STEP_METRIC_INFO_PREFIX = "step_metric_"
EPISODE_END_REASON_WINDOW_SIZE = 100
