import struct

NANOSECONDS_PER_SECOND = 1_000_000_000
MILLISECONDS_PER_SECOND = 1_000

TRANSPORT_ACQUIRE_RETRY_TIMEOUT_SECONDS = 0.1
ASSEMBLER_RECEIVE_TIMEOUT_SECONDS = 0.1
WORKER_HEALTH_CHECK_INTERVAL_SECONDS = 0.1
PROCESS_EXIT_ATTRIBUTION_TIMEOUT_SECONDS = 1.0
SHARED_COUNTER_TYPE_CODE = "q"
SHARED_SLOT_INDEX_TYPE_CODE = "i"
SHARED_SIZE_TYPE_CODE = "Q"
POLICY_SNAPSHOT_SLOT_COUNT = 2
POLICY_INITIAL_SLOT_INDEX = 0
POLICY_UNPUBLISHED_VERSION = -1
EPISODE_PACKET_HEADER = struct.Struct("!BqBQ")
EPISODE_KIND_ON_POLICY_CODE = 0
EPISODE_KIND_OFF_POLICY_CODE = 1

BUFFER_AVG_POLICY_LAG_KEY = "avg_policy_lag"
BUFFER_MAX_POLICY_LAG_KEY = "max_policy_lag"
BUFFER_AVG_PUSH_WAIT_SECONDS_KEY = "avg_push_wait_seconds"

ON_POLICY_ENVIRONMENT_REWARDS_FIELD = "environment_rewards"
ON_POLICY_TRAINING_REWARDS_FIELD = "training_rewards"
OFF_POLICY_REWARDS_FIELD = "rewards"

ASYNC_WORKER_FAILURE_MESSAGE = "Async workers failed: {failures}"
WORKER_FAILURE_MESSAGE = "worker {worker_index}: {reason}"
WORKER_TRANSPORT_CLOSED_REASON = "episode transport closed"
